version: "3.8"
services:
  docsearch-dev:
    build: .devcontainer
    tty: true
    container_name: docsearch-dev
    volumes:
      - .:/src/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    environment:
      TZ: Asia/Tokyo
    networks:
      - docsearch-net
networks:
  default:
    name: bridge
  docsearch-net:
    name: docsearch-net
    driver: bridge
